name: main
on:
  push:
  pull_request:

jobs:
  build:
    name: Update to Expo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Logging
        run: |
          echo "${{toJSON(github.event)}}"
      - name: Test
        run: echo $GITHUB_REF_NAME
